### ISSUE TITLE
Add operation to insert message in SQS queue

### ISSUE THREAD

**Issue by laveeshb** [laveeshb/azure-function-extensions-net#25]

**Comment by laveeshb** [comment]
@juanmjacobs I have published a new version of the package to nuget

**Comment by juanmjacobs** [comment]
> @juanmjacobs I have published a new version of the package to nuget

Awesome! I'll be using it in the next few days. Thank you for your time!

**Comment by laveeshb** [comment]
📦 The SQS extension has been moved to a dedicated repository: https://github.com/laveeshb/azure-functions-sqs-extension
