### ISSUE TITLE
AutoResolve for SQS Extension

### ISSUE THREAD

**Issue by juanmjacobs** [laveeshb/azure-function-extensions-net#35]
Hi, how are you? This is a great project, thank you very much for sharing it!
I'm trying to run the SQS Extension on a JS worker.
Could you please add `[AutoResolve]` for the [SQS extension configuration properties](https://github.com/laveeshb/azure-function-extensions-net/blob/2ead332f244e8f0c3d78e98d6e6e4b912accf3cb/Amazon.SQS/src/Extensions.SQS/Trigger/SqsQueueTriggerAttribute.cs#L9)?
I've noticed that the other extensions have the AutoResolve attribute, but not this one.
I think that just adding the attribute would allow a `function.json` to specify environment variable names instead of hardcoded values.
```
{
  "disabled": false,
  "bindings": [{
      "name": "message",
      "type": "sqsQueueTrigger",
      "direction": "in",
      "queueName": "myQueue",
      "QueueUrl": "AWS_QUEUE_URL",
      "AWSKeyId": "AWS_KEY_ID",
      "AWSAccessKey": "AWS_ACCESS_KEY"
    }
  ]
}
```
Thank you for your time!

**Comment by laveeshb** [comment]
Thank you for your contribution. I'll review your change.

**Comment by laveeshb** [comment]
@juanmjacobs I have published the package here https://www.nuget.org/packages/AzureFunctions.Extension.SQS/1.1.0. Here are the release notes -- https://github.com/laveeshb/azure-function-extensions-net/releases/tag/amazon.sqs-v1.1.0

**Comment by laveeshb** [comment]
📦 The SQS extension has been moved to a dedicated repository: https://github.com/laveeshb/azure-functions-sqs-extension
